module.exports = {
  mainSidebar: {
    Moloch: ['docs/contracts', 'docs/subgraphs'],
    Client: [
      'docs/dev-proposals',
      'docs/activities',
      'docs/bank',
      'docs/contexts',
      'docs/services',
      'docs/tx-polling',
      'docs/summoning',
      'docs/utilities',
    ],
    Boosts: ['docs/default-boosts', 'docs/new-boosts'],
    'JS Code Review': [
      'docs/goals-and-ideals',
      'docs/review-process',
      'docs/javascript',
      'docs/async-await',
      'docs/caching',
      'docs/react-structure',
      'docs/react-components',
      'docs/react-use-effect',
      'docs/react-jsx',
      'docs/react-layout',
    ],
  },
  howSidebar: {
    Intro: ['intro', 'intro-dao', 'intro-moloch', 'glossary'],
    Basics: ['bank', 'membership', 'proposals-intro', 'profile'],
    HowTo: [
      'navigation',
      'hub',
      'summon',
      'add-member',
      'request-funding',
      'withdraw-internal',
      'weth',
      'networks',
    ],
    UberHaus: ['uberhaus-governance', 'cco', 'uber-actions'],
  },
};
