module.exports = {
  mainSidebar: {
    Moloch: ["developers/contracts", "developers/subgraphs"],
    Client: [
      "developers/dev-proposals",
      "developers/activities",
      "developers/bank",
      "developers/contexts",
      "developers/services",
      "developers/tx-polling",
      "developers/summoning",
      "developers/utilities",
    ],
    Boosts: ["developers/default-boosts", "developers/new-boosts"],
    "JS Code Review": [
      "developers/goals-and-ideals",
      "developers/javascript",
      "developers/async-await",
      "developers/caching",
      "developers/react-structure",
      "developers/react-components",
      "developers/react-use-effect",
      "developers/react-jsx",
    ],
  },
  howSidebar: {
    Intro: ["intro", "intro-dao", "intro-moloch", "glossary"],
    Basics: ["treasury", "membership", "proposals-intro", "profile"],
    HowTo: [
      "navigation",
      "hub",
      "summon",
      "add-member",
      "request-funding",
      "withdraw-internal",
      "weth",
      "networks",
    ],
    UberHaus: ["uberhaus-governance", "cco", "uber-actions"],
  },
};
