module.exports = {
  mainSidebar: {
    Moloch: ['devs/contracts', 'devs/subgraphs'],
    Client: [
      {
        'Code Legos': [
          'devs/legos/overview',
          'devs/legos/tx-tut',
          'devs/legos/tx-api',
          'devs/legos/field-lego-api',
          'devs/legos/form-lego-api',
        ],
      },
      'devs/dev-proposals',
      'devs/activities',
      'devs/bank',
      'devs/contexts',
      'devs/services',
      'devs/tx-polling',
      'devs/summoning',
      'devs/utilities',
    ],
    Boosts: ['devs/default-boosts', 'devs/new-boosts'],
    'JS Code Review': [
      'devs/goals-and-ideals',
      'devs/review-process',
      'devs/javascript',
      'devs/async-await',
      'devs/caching',
      'devs/react-structure',
      'devs/react-components',
      'devs/react-use-effect',
      'devs/react-jsx',
      'devs/react-layout',
    ],
  },
  howSidebar: {
    Intro: [
      'users/intro',
      'users/intro-dao',
      'users/intro-moloch',
      'users/glossary',
    ],
    Features: [
      'users/hub',
      'users/bank',
      'users/membership',
      'users/proposals-intro',
      'users/profile',
      'users/minion',
      'users/boosts',
    ],
    Tutorials: [
      'users/navigation',
      'users/summon',
      'users/add-mintgate-boost',
      'users/add-member',
      'users/deploy-minion',
      'users/request-funding',
      'users/withdraw-internal',
      'users/weth',
      'users/networks',
      'users/manage-proposal-playlists',
    ],
    FAQ: [
      'users/proposals-faq',
      'users/bank-faq',
      'users/members-faq',
      'users/summoner-faq',
      'users/settings-faq',
      'users/boosts-faq',
      'users/allies-faq',
      'users/profile-faq',
      'users/minion-faq',
      'users/other-networks-faq',
    ],
  },
  whoSidebar: {
    Community: [
      'handbook/who-we-are',
      'handbook/meeting-schedule',
      'handbook/resources',
    ],
    Discord: [
      'handbook/getting-started',
      //"handbook/level-up",
      'handbook/scholar',
      'handbook/supporter',
      'handbook/contributor',
      'handbook/summoner',
      'handbook/discord-faq',
      //"handbook/bots"
    ],
    Summoners: [
      'handbook/summoners/why-daos-summoners',
      {
        type: 'category',
        label: 'Features',
        items: [
          'handbook/summoners/summoners-daohaus-features',
          'handbook/summoners/uberhaus-governance',
          'handbook/summoners/cco',
        ],
      },
      {
        type: 'category',
        label: 'Tutorials',
        items: [
          'handbook/summoners/summoners-get-started',
          'handbook/summoners/summon-dao-gnosis',
          'handbook/summoners/uber-actions',
        ],
      },
      'handbook/summoners/summoners-best-practices',
      'handbook/summoners/summoners-faq',
    ],
    Contributors: [
      'handbook/contributors/contributors-get-started',
      'handbook/contributors/contributors-docs',
      'handbook/contributors/contributors-docs-style-guide',
      'handbook/contributors/contributors-get-paid',
      'handbook/contributors/contributors-earn-power',
      'handbook/contributors/contributors-faq',
    ],
    Circles: [
      'handbook/overview',
      'handbook/alchemists',
      'handbook/magesmiths',
      'handbook/paladins',
      'handbook/rangers',
      'handbook/uberpaladins',
    ],
  },
};
``;
